/* Generated by scripts/gen_ferro_palette.py - do not hand-edit.
 *
 * Each palette is one monitor phosphor at two drive levels (lospec's Obra Dinn set):
 * the pair is ground and bright, blob is interpolated between them in linear light at
 * t - solved so every palette shares one blobs:ground contrast ratio - and dim is a
 * luminance-weighted mean of blob and bright, biased toward blob
 * (DIM_BIAS) so the idle indicators sit back. All four are sRGB; LVGL quantises
 * to RGB565 itself. */

#include "ferro_palette.h"

#include <zephyr/kernel.h>

/* Number of rows the generator wrote. If it disagrees with FERRO_PALETTE_COUNT the array is
 * padded with zeros and the palette cycle lands on a black screen. */
#define FERRO_PALETTE_GEN_COUNT 6
BUILD_ASSERT(FERRO_PALETTE_GEN_COUNT == FERRO_PALETTE_COUNT,
             "ferro_palette.h count disagrees with the generated table");

const struct ferro_palette ferro_palettes[FERRO_PALETTE_COUNT] = {
    /* MACINTOSH  t=0.15 */
    {.name = "Macintosh", .ground = 0x333319, .blob = 0x69746D, .dim = 0x91A09D, .bright = 0xE5FFFF},
    /* IBM8503    t=0.17 */
    {.name = "IBM 8503", .ground = 0x2E3037, .blob = 0x727068, .dim = 0x9A9689, .bright = 0xEBE5CE},
    /* IBM5151    t=0.23 */
    {.name = "IBM 5151", .ground = 0x25342F, .blob = 0x20813E, .dim = 0x1BA548, .bright = 0x01EB5F},
    /* ZENITH     t=0.21 */
    {.name = "Zenith ZVM 1240", .ground = 0x3F291E, .blob = 0x876930, .dim = 0xAF8A3C, .bright = 0xFDCA55},
    /* COMMODORE  t=0.31 */
    {.name = "Commodore 1084", .ground = 0x40318E, .blob = 0x5E85AC, .dim = 0x6CA2BC, .bright = 0x88D7DE},
    /* MONO       t=0.10 */
    {.name = "Mono", .ground = 0x000000, .blob = 0x515151, .dim = 0x828282, .bright = 0xEBEBEB},
};
