#!/usr/bin/env python3
"""Emit the flux line endpoint table as C.

Run from anywhere; writes
boards/shields/prospector_adapter/src/layouts/flux/line_endpoints.h.
"""
import math
import pathlib

OUT = "boards/shields/prospector_adapter/src/layouts/flux/line_endpoints.h"

NUM_ANGLES = 180
ANGLE_STEP = 2
LENGTH = 14


def render():
    out = [
        "/* Auto-generated by scripts/gen_line_endpoints.py */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define LINE_ENDPOINT_NUM_ANGLES {NUM_ANGLES}",
        f"#define LINE_ENDPOINT_ANGLE_STEP {ANGLE_STEP}",
        f"#define LINE_ENDPOINT_LENGTH {LENGTH}",
        "",
        "/* Pre-computed endpoints: dx = cos(angle) * length, dy = sin(angle) * length */",
        f"static const int8_t line_endpoints[{NUM_ANGLES}][2] = {{",
    ]
    for i in range(NUM_ANGLES):
        deg = i * ANGLE_STEP
        r = math.radians(deg)
        dx = round(math.cos(r) * LENGTH)
        dy = round(math.sin(r) * LENGTH)
        out.append(f"    {{{dx:3d}, {dy:3d}}},  /* {deg:3d}° */")
    out += ["};", ""]
    return "\n".join(out)


if __name__ == "__main__":
    (pathlib.Path(__file__).resolve().parent.parent / OUT).write_text(render())
