#!/usr/bin/env python3
"""Emit the ferro palette table as C.

The linear-light derivation lives here, not in the firmware: the device only ever reads
four sRGB triples per palette. Run from anywhere; writes
boards/shields/prospector_adapter/src/layouts/ferro/ferro_palette_table.c.
"""
import pathlib

OUT = ("boards/shields/prospector_adapter/src/layouts/ferro/ferro_palette_table.c")

# name, ground, bright: one monitor phosphor at two drive levels, from lospec's Obra Dinn set.
PAL = [
    ("Macintosh", "MACINTOSH", "333319", "e5ffff"),
    ("IBM 8503", "IBM8503", "2e3037", "ebe5ce"),
    ("IBM 5151", "IBM5151", "25342f", "01eb5f"),
    ("Zenith ZVM 1240", "ZENITH", "3f291e", "fdca55"),
    ("Commodore 1084", "COMMODORE", "40318e", "88d7de"),
    ("Mono", "MONO", "000000", "ebebeb"),
]

# The blob level is a pick on the Mono pair, held as a blobs:ground contrast ratio rather
# than as t: the pairs differ in total range, so a fixed t gave Commodore a 1.52:1 step
# against Mono's 2.65:1 and the halftone read quieter on some palettes for no reason but
# the pair. Each palette's t is solved for that anchor instead.
MONO_T = 0.10

# Where dim sits between blob and bright, as a weight on the geometric mean in luminance.
# 0.5 is the equal-contrast-steps rule the tone was derived with; higher pulls it toward
# the blob, spending a little of the dim:blob step to let idle indicators sit back further.
DIM_BIAS = 0.62


def h2(h):
    return [int(h[i:i + 2], 16) for i in (0, 2, 4)]


def lin(u):
    u /= 255.0
    return u / 12.92 if u <= 0.04045 else ((u + 0.055) / 1.055) ** 2.4


def enc(v):
    v = max(0.0, min(1.0, v))
    s = v * 12.92 if v <= 0.0031308 else 1.055 * v ** (1 / 2.4) - 0.055
    return int(round(s * 255))


def Y(c):
    return 0.2126 * lin(c[0]) + 0.7152 * lin(c[1]) + 0.0722 * lin(c[2])


def ramp(i):
    """The pair's linear-light ramp: ground, bright, and the sRGB colour at t."""
    g, b = h2(PAL[i][2]), h2(PAL[i][3])
    lg, lb = [lin(v) for v in g], [lin(v) for v in b]
    return g, b, (lambda u: [enc(lg[k] + u * (lb[k] - lg[k])) for k in range(3)])


def lv(c):
    return "0x%02X%02X%02X" % tuple(c)


def rows():
    _g, _b, _at = ramp([p[1] for p in PAL].index("MONO"))
    anchor = (Y(_at(MONO_T)) + 0.05) / (Y(_g) + 0.05)

    out = []
    for i, (name, pid, _, _) in enumerate(PAL):
        g, b, at = ramp(i)
        Yg, Yw = Y(g), Y(b)
        t = (anchor * (Yg + 0.05) - 0.05 - Yg) / (Yw - Yg)
        blob = at(t)
        Ym = ((Yw + 0.05) ** (1 - DIM_BIAS)) * ((Y(blob) + 0.05) ** DIM_BIAS) - 0.05
        dim = at((Ym - Yg) / (Yw - Yg))
        out.append((name, pid, g, blob, dim, b, t))
    return out


def render(rs):
    out = [
        "/* Generated by scripts/gen_ferro_palette.py - do not hand-edit.",
        " *",
        " * Each palette is one monitor phosphor at two drive levels (lospec's Obra Dinn set):",
        " * the pair is ground and bright, blob is interpolated between them in linear light at",
        " * t - solved so every palette shares one blobs:ground contrast ratio - and dim is a",
        " * luminance-weighted mean of blob and bright, biased toward blob",
        " * (DIM_BIAS) so the idle indicators sit back. All four are sRGB; LVGL quantises",
        " * to RGB565 itself. */",
        "",
        '#include "ferro_palette.h"',
        "",
        "#include <zephyr/kernel.h>",
        "",
        "/* Number of rows the generator wrote. If it disagrees with FERRO_PALETTE_COUNT the array is",
        " * padded with zeros and the palette cycle lands on a black screen. */",
        f"#define FERRO_PALETTE_GEN_COUNT {len(rs)}",
        "BUILD_ASSERT(FERRO_PALETTE_GEN_COUNT == FERRO_PALETTE_COUNT,",
        '             "ferro_palette.h count disagrees with the generated table");',
        "",
        "const struct ferro_palette ferro_palettes[FERRO_PALETTE_COUNT] = {",
    ]
    for name, pid, g, blob, dim, b, t in rs:
        out.append(f"    /* {pid:10s} t={t:.2f} */")
        out.append(f'    {{.name = "{name}", .ground = {lv(g)}, .blob = {lv(blob)}, '
                   f".dim = {lv(dim)}, .bright = {lv(b)}}},")
    out += ["};", ""]
    return "\n".join(out)


if __name__ == "__main__":
    rs = rows()
    (pathlib.Path(__file__).resolve().parent.parent / OUT).write_text(render(rs))
